name: garrita_perdida_app
description: Dona, Adopta y Rescata.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0
  bloc: ^8.0.1
  buildcondition: ^0.0.4
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.5
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1

  flutter_svg: ^1.0.0
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  intl:  ^0.17.0
  material_floating_search_bar: ^0.3.6
  path: ^1.8.2
  path_provider: ^2.0.11
  pushable_button: ^0.0.2
  queen_validators: ^1.0.1
  shared_preferences: ^2.0.11
  smooth_page_indicator: ^1.0.0+2
  transparent_image: ^2.0.0
  url_launcher: ^6.0.18
  uuid: ^3.0.5
 
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/icon/logo.png"
 adaptive_icon_background: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-Regular.otf
